export const CLEANUP = 'CLEANUP';
export const ASYNC_NOOP = 'ASYNC_NOOP';
export const ASYNC_GET_MANY_POST = 'ASYNC_GET_MANY_POST';
export const ASYNC_DELETE_ONE_POST = 'ASYNC_DELETE_ONE_POST';
export const ASYNC_PATCH_ONE_POST = 'ASYNC_PATCH_ONE_POST';
export const ACCEPT_UPDATE_POST_LIST = 'ACCEPT_UPDATE_POST_LIST';
export const ASYNC_GET_ONE_USER_BY_POST_ID = 'ASYNC_GET_ONE_USER_BY_POST_ID';
