export const CLEANUP = 'CLEANUP';
export const ASYNC_NOOP = 'ASYNC_NOOP';
export const ASYNC_GET_MANY_TODO = 'ASYNC_GET_MANY_TODO';
export const ASYNC_DELETE_ONE_TODO = 'ASYNC_DELETE_ONE_TODO';
export const ASYNC_PATCH_ONE_TODO = 'ASYNC_PATCH_ONE_TODO';
export const ACCEPT_UPDATE_TODO_LIST = 'ACCEPT_UPDATE_TODO_LIST';
export const ASYNC_GET_ONE_USER_BY_TODO_ID = 'ASYNC_GET_ONE_USER_BY_TODO_ID';
