export const PAGE_SIZE_OF_POST_LIST = 5;
export const LOCAL_STORAGE_REDUX_STORE_KEY = 'REDUX-SAGA-MATE-DEMO-REDUX-STORE';
export const LOCAL_STORAGE_PATH_BEFORE_404 = 'REDUX-SAGA-MATE-DEMO-PATH-BEFORE-404';
